/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iitb_interactiveclassroom_AudioSession */

#ifndef _Included_com_iitb_interactiveclassroom_AudioSession
#define _Included_com_iitb_interactiveclassroom_AudioSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iitb_interactiveclassroom_AudioSession
 * Method:    Java_speex_EchoCanceller_open
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_iitb_interactiveclassroom_AudioSession_Java_1speex_1EchoCanceller_1open
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_iitb_interactiveclassroom_AudioSession
 * Method:    Java_speex_EchoCanceller_process
 * Signature: ([S[S)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_iitb_interactiveclassroom_AudioSession_Java_1speex_1EchoCanceller_1process
  (JNIEnv *, jobject, jshortArray, jshortArray);

/*
 * Class:     com_iitb_interactiveclassroom_AudioSession
 * Method:    Java_speex_EchoCanceller_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iitb_interactiveclassroom_AudioSession_Java_1speex_1EchoCanceller_1close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
